file(MAKE_DIRECTORY "${OUTPUT_DIR}")
function(run exe operation directory)
    execute_process(COMMAND "${exe}" "${operation}" "${directory}" RESULT_VARIABLE result)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "${exe} ${operation} failed: ${result}")
    endif()
endfunction()
run("${STD_EXE}" generate "${OUTPUT_DIR}/std")
run("${QT_EXE}" verify "${OUTPUT_DIR}/std")
run("${QT_EXE}" generate "${OUTPUT_DIR}/qt")
run("${STD_EXE}" verify "${OUTPUT_DIR}/qt")
